# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(1015, 850)
        self.centralwidget = QtWidgets.QWidget(MenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 240, 1011, 481))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 1001, 441))
        self.label_4.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 70, 1001, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(0, 40, 91, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(900, 400, 101, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 400, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 70, 1001, 321))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(0, 40, 91, 21))
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(870, 400, 131, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(732, 400, 121, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 70, 1001, 321))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(0, 40, 91, 21))
        self.label_7.setObjectName("label_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(872, 400, 131, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(740, 400, 121, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 70, 1001, 321))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(0, 40, 91, 21))
        self.label_8.setObjectName("label_8")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_8.setGeometry(QtCore.QRect(870, 400, 131, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_9.setGeometry(QtCore.QRect(740, 400, 121, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_9 = QtWidgets.QLabel(self.tab_6)
        self.label_9.setGeometry(QtCore.QRect(390, 180, 201, 41))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_10 = QtWidgets.QLabel(self.tab_7)
        self.label_10.setGeometry(QtCore.QRect(370, 180, 201, 41))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_11 = QtWidgets.QLabel(self.tab_8)
        self.label_11.setGeometry(QtCore.QRect(380, 180, 201, 41))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_12 = QtWidgets.QLabel(self.tab_9)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 791, 261))
        self.label_12.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab_9, "")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 760, 1001, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 201, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(790, 30, 201, 191))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(620, 40, 151, 141))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 381, 211))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 740, 72, 15))
        self.label_3.setIndent(-8)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(622, 197, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        MenuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 26))
        self.menubar.setObjectName("menubar")
        MenuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuWindow)
        self.statusbar.setObjectName("statusbar")
        MenuWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MenuWindow)
        self.tabWidget.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "QEFT"))
        self.label_4.setText(_translate("MenuWindow", "# QEFT(基于开源项目edl的GUI高通刷机程序)\n"
"\n"
"# 目前处于开发阶段，可能无法使用\n"
"\n"
"## 本项目基于[edl](https://github.com/bkerler/edl)开源项目开发，遵守GPL-V3开源协议\n"
"\n"
"## ZH_CN/[English](EN_README.md)\n"
"\n"
"### 项目简介\n"
"\n"
"#### QEFT是一个基于开源项目edl的GUI高通刷机程序，旨在简化高通设备的刷机过程。QEFT使用Python编写，使用PyQt5作为GUI框架，提供了一个直观的用户界面，方便用户进行刷机操作。\n"
"#### 结构（开发说明）\n"
"- main.py：主程序，负责启动GUI界面\n"
"- core文件夹:核心逻辑（待编写）\n"
"- ui文件夹：存放GUI界面的设计文件\n"
"- - qeft_main_window.py：主窗口的设计文件\n"
"- - qeft_start_window.py：启动窗口的设计文件\n"
"- res文件夹：存放资源文件\n"
"- - edl文件夹：存放edl项目文件\n"
"\n"
"### 开发说明\n"
"可以参考API文档\n"
"[BK_EDLClient_API文档](BK_EDLVLIENT_API_README.md)\n"
"~~~\n"
"注意：本项目基于开源项目edl开发，项目代码中未包含edl项目的代码，刷机前请先下载/克隆edl项目并将其放入edl文件夹中。\n"
"\n"
"cd res\n"
"git clone https://github.com/bkerler/edl.git\n"
"pip3 install -r requriements.txt\n"
"~~~\n"
"\n"
"## 开发目标：2025/6/14更新\n"
"### 本次开发目标\n"
"#### 完善设备识别和加载逻辑（可以参考edl仓库readme和api文档）\n"
"#### 完善主界面（qeft_menu_window.py/menu.ui）\n"
"### 截至到7/05日\n"
"---\n"
"\n"
"### 食用说明\n"
"[BK_EDLClient_API文档](BK_EDLVLIENT_API_README.md)\n"
"\n"
"### 贡献\n"
"#### *630*\n"
"#### *kirin7098*\n"
"#### *huang1057*\n"
"~~~\n"
"+ 基于https://github.com/bkerler/edl的开源项目开发，遵守GPL-V3开源协议\n"
"~~~\n"
"#### 欢迎贡献代码\n"
"##### 可以在issue中提出建议，也可以直接提交PR\n"
"##### 代码贡献需要遵循GPL-V3开源协议\n"
"##### 代码贡献需要有一定的Python和PyQt5开发经验"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MenuWindow", "主页"))
        self.label_5.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">分区列表</span></p></body></html>"))
        self.pushButton.setText(_translate("MenuWindow", "管理所选项"))
        self.pushButton_2.setText(_translate("MenuWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MenuWindow", "分区管理"))
        self.label_6.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">分区列表</span></p></body></html>"))
        self.pushButton_4.setText(_translate("MenuWindow", "清除所选分区"))
        self.pushButton_5.setText(_translate("MenuWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MenuWindow", "分区清除"))
        self.label_7.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">分区列表</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MenuWindow", "回读所选分区"))
        self.pushButton_7.setText(_translate("MenuWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MenuWindow", "分区回读"))
        self.label_8.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">分区列表</span></p></body></html>"))
        self.pushButton_8.setText(_translate("MenuWindow", "刷写所选分区"))
        self.pushButton_9.setText(_translate("MenuWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MenuWindow", "分区刷写"))
        self.label_9.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">正在开发: )</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MenuWindow", "超级恢复专用"))
        self.label_10.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">正在开发: )</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MenuWindow", "QEFT自动化脚本设计"))
        self.label_11.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">正在开发: )</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MenuWindow", "常用工具"))
        self.label_12.setText(_translate("MenuWindow", "### 贡献人员\n"
"#### *630*\n"
"#### *kirin7098*\n"
"#### *huang1057*\n"
"---\n"
"### 未来可能会有你！\n"
"~~~\n"
"+ 基于https://github.com/bkerler/edl的开源项目开发，遵守GPL-V3开源协议\n"
"~~~\n"
"#### 欢迎贡献代码\n"
"##### 可以在issue中提出建议，也可以直接提交PR\n"
"##### 代码贡献需要遵循GPL-V3开源协议\n"
"##### 代码贡献需要有一定的Python和PyQt5开发经验"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MenuWindow", "关于"))
        self.label.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">设备信息</span></p><p><span style=\" font-size:11pt; font-weight:600;\">名称：{占位符}</span></p><p><span style=\" font-size:11pt; font-weight:600;\">端口：{占位符}</span></p><p><span style=\" font-size:11pt; font-weight:600;\">SOC:{占位符}</span></p><p><br/></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">QC EDL Flash Tool</span></p><p><span style=\" font-size:10pt;\">QEFT</span></p><p><span style=\" font-size:10pt;\">版本：V0.0</span></p><p><span style=\" font-size:10pt;\">基于bkerler的开源项目edl创建</span></p><p><span style=\" font-size:10pt;\">基于GPL-V3许可证开源</span></p><p><span style=\" font-size:10pt;\">违反该许可证可能迫使我们停止开发/开源该项目！</span></p></body></html>"))
        self.label_3.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">进度</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MenuWindow", "重启设备"))
