# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StartSettingsWindow(object):
    def setupUi(self, StartSettingsWindow):
        StartSettingsWindow.setObjectName("StartSettingsWindow")
        StartSettingsWindow.resize(629, 416)
        self.centralwidget = QtWidgets.QWidget(StartSettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        StartSettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartSettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 26))
        self.menubar.setObjectName("menubar")
        StartSettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartSettingsWindow)
        self.statusbar.setObjectName("statusbar")
        StartSettingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StartSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(StartSettingsWindow)

    def retranslateUi(self, StartSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        StartSettingsWindow.setWindowTitle(_translate("StartSettingsWindow", "连接设置"))

